Fix Mann address bug (#301)
* Merge changes for v5.4 (#300)

* Update release notes

* Update tests and Rails v7 (#295)

* Update release notes (#294)

* Update Rails to v7.0; remove oracle

There's apparently an incompatibility between Rails 6.x and Ruby 3.2:

"
NameError: uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger

"This is a known issue when using Ruby 3.2+ with Rails 6.1.
Rails 6.1 is not fully compatible with Ruby 3.2. The LoggerThreadSafeLevel::Logger constant was removed from Ruby's standard library, but Rails 6.1 still references it."

Upgrading to Rails 7 fixed the issue I was having with RSpec not running.

I don't think we've needed the Oracle dependency for a while. Faced with trying to recompile a new
version for native extensions after updating Rails, this seemed like an opportune time to finally
get rid of it.

* Get RSpec to run

* Add initial rspec tests for request_controller

* Add HEAD test

* Add tests

* Add simplecov gem for code test coverage analysis

* Add tests

* Additional controller tests

* Add tests for ReShare

* Add tests for request_helper

* Add tests for patron model

* Fix typo

* Add tests for volume model

* Add tests for item model

* Tests for delivery_method

* Additional controller tests

* Bump to v5.4

* Comment cleanup

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>

* Delete circ policy table (#297)

* Update release notes (#294)

* Remove obsolete circ_policy_locs table/model

* Simplify migration

* Use extended table name

* Delete old tests

* Update release notes

* Remove protected_attributes_continued dependency

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>

* Migrate migrations (#298)

* Update release notes (#294)

* Remove references to CircPolicyLocs model from migrations

* Comments

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>

* DACCESS-92: Prepopulate Mann Special Collections link (#299)

* Update release notes (#294)

* Update Mann Special Collections link builder to prepopulate form fields (DACCESS-92)

* Update tests

* Still return link if there's no patron record

* Update release_notes

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>

* Update release notes

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>

* Add test for Mann SD link builder bug

* Add test for Mann SD link builder bug

* Fix bug in building address part of Mann special collections link

* Update release notes

---------

Co-authored-by: sarah-cul <144364984+sarah-cul@users.noreply.github.com>